### ISSUE TITLE
Not compatible with gem que-2.2

### ISSUE THREAD

**Issue by bharat55** [statianzo/que-web#101]
I have updated my que gem from `que-1.4` to gem `que-2.2` and seems like this que-web is not compatible with that

Here are my error logs

```

Bundler could not find compatible versions for gem "que":
  In Gemfile:
    que (~> 2.2)

    que-web (~> 0.9.4) was resolved to 0.9.4, which depends on
      que (~> 1)

```

**Comment by keithlayne** [comment]
Looks like the fix was merged, but there wasn't a release.

**Comment by yifeiwu** [comment]
@morgoth

**Comment by statianzo** [comment]
Pushed a new release [0.10.0](https://rubygems.org/gems/que-web/versions/0.10.0)
