### ISSUE TITLE
Show processed jobs

### ISSUE THREAD

**Issue by Mbuckley0** [statianzo/que-web#23]
It would be great to be able to see the number of jobs and inspect the particular jobs which have processed successfully on the webpage.

**Comment by statianzo** [comment]
Unfortunately, that's not a value persisted by que. When a job is finished, it's deleted from the table and there is no statistics storage.

**Comment by alhafoudh** [comment]
`que` now supports marking the job as finished without destroying it. Can we reflect this in `que-web`?

**Comment by statianzo** [comment]
@alhafoudh can you write a PR that reflects it?
