### ISSUE TITLE
UndefinedColumn at /running

### ISSUE THREAD

**Issue by ericboehs** [statianzo/que-web#25]
I can not access the `/running` route with Que schema version 3.

I get an error saying the column `pg_waiting_on_lock` does not exist.

I believe this is an issue for everyone using the newer version of Que.

**Comment by morgoth** [comment]
@ericboehs Que 1.0.0 will require schema version 4 https://github.com/que-rb/que/blob/master/CHANGELOG.1.0.beta.md#100beta-2017-10-25 which works fine with current que-web
Do you stil have this issue?

**Comment by morgoth** [comment]
please reopen if you're still having issues
