### ISSUE TITLE
Support for Que 1.0

### ISSUE THREAD

**Issue by sidonath** [statianzo/que-web#44]
Hi there and thanks for all the work on que-web!

Que 1.0 beta releases have been coming out steadily, but they are not backwards compatible with 0.* branch.

Are there any plans for que-web to support the new versions?

**Comment by statianzo** [comment]
Do you have any insight to what has changed? I'm open to pull requests to make this work.

**Comment by sidonath** [comment]
To be honest, I just started using Que, so I can't really provide a summary 😅  It seems the schema change would be one of the bigger issues.

There's [a detailed changelog](https://github.com/chanks/que/blob/master/CHANGELOG.1.0.beta.md), though.

**Comment by brunoporto** [comment]
https://github.com/statianzo/que-web/pull/46

**Comment by sidonath** [comment]
Since the fix was merged, I'll close this issue.

Thanks @brunoporto! <3
