### ISSUE TITLE
Missing `present?` method

### ISSUE THREAD

**Issue by janlelis** [statianzo/que-web#45]
The project seems to require an implementaiton of `.present?` - See here: https://github.com/statianzo/que-web/blob/v0.7.1/lib/que/web.rb#L154

I can get `que-web` it to work when I add the following line to my Gemfile:

    gem 'activesupport', require: 'active_support/core_ext/object/blank'

Am I missing something, like a different library that provides the `.present?` implementation?

**Comment by statianzo** [comment]
@janlelis the unlisted dependency on activesupport was added unintentionally during a previous pull request. The usage of `present?` was removed in https://github.com/statianzo/que-web/commit/6f10b3116dd4a38441077602d3bb64faef20228e

I just released v0.7.2 with that change to drop the dependency.

**Comment by janlelis** [comment]
Awesome, thank you very much!
