### ISSUE TITLE
Templates rendering as strings not markup

### ISSUE THREAD

**Issue by adzap** [statianzo/que-web#67]
Removal of erubis in this commit https://github.com/statianzo/que-web/commit/25962a2e4ae43dd739890a7d904cfbc0fc3d31ac caused regression in template rendering. 

Still need double equals.

**Comment by statianzo** [comment]
@adzap where is this failing? Could you share a stack trace?

@morgoth could you take a look?

**Comment by adzap** [comment]
@statianzo No error, just the templates render as a quoted string not as markup. See below image

![Que_Web_and_Statement_Lines_Report_2020-03-12](https://user-images.githubusercontent.com/6318/78100174-c1af5680-742f-11ea-965d-a87a23ff0a6b.png)

**Comment by morgoth** [comment]
Sorry for this. I did my final testing on `examples/rack` app which has different setup than sinatra app that is actually used.
@statianzo could you please release 0.9.1 with this fix?

**Comment by statianzo** [comment]
@morgoth 0.9.1
