### ISSUE TITLE
release 0.9.2

### ISSUE THREAD

**Issue by morgoth** [statianzo/que-web#70]
@statianzo Could you release 0.9.2 with 2 small bugfixes https://github.com/statianzo/que-web/blob/master/CHANGELOG.md#092---unreleased

Eventually you could add me as a gem owner, so I can also release it if you don't mind.
My email at rubygems is "w.wnetrzak@gmail.com" https://rubygems.org/profiles/morgoth

**Comment by statianzo** [comment]
Added you as an owner. Feel free to test releasing 0.9.2

**Comment by morgoth** [comment]
Pushed. Thank you.
