### ISSUE TITLE
Can't actually retry expired jobs

### ISSUE THREAD

**Issue by swrobel** [statianzo/que-web#73]
This isn't a que-web bug _per se_, but it is a bit confusing. If a job's `error_count` has exceeded `max_retry_count` and `expired_at` has a value, this job is effectively "dead" and yet que-web allows you to retry it, and gives the impression that it has been retried (`run_at` updates) - yet the job is not actually re-run. I don't know if there's a way around this, though I've opened [an issue](https://github.com/que-rb/que/issues/288) with que to find out - if so, we should fix in que-web, otherwise add some logic to disable the retry button for such jobs.

**Comment by statianzo** [comment]
I'm onboard with having the ability to retry expired jobs. Would give a way to manually deal with dead jobs beyond deleting.

Maybe setting `expired_at=NULL` on retry would be enough given the `:poll_jobs` SQL doesn't pay any attention to `error_count`, it only looks for `expired_at IS NULL`.
