### ISSUE TITLE
Returns part of HTML

### ISSUE THREAD

**Issue by FlintOFF** [statianzo/que-web#79]
For some reason, it returns only a part of HTML page:
* on 'running' page I see a withe page, and it returns only a part of HTML (only part of the header, without the body)
* on 'scheduled' page I see only 2 jobs from 7, and I can't see any actions buttons at the bottom of the page
* on 'failing' page I see only 6 jobs from 289 without paginations and actions buttons at the bottom of the page

Gems:
* locks (0.2.0)
* que-scheduler (3.3.0)
* que-web (0.9.3)
* que (1.0.0.beta4)

Works great on the local machine but have an issue on Heroku production server

Could you please help to understand where can be the issue

**Comment by morgoth** [comment]
It's hard to say. I run app on heroku and it works without a problem for me (I don't use locks nor que-scheduler gems).

Do you have any javascript errors in browser console? Just a wild guess...

**Comment by FlintOFF** [comment]
Hello. Thanks for the answer.
No, I do not see any problems in the console on both servers. 
I just copied DB from production to staging server and still have the issue (the code absolutely the same and the page also same).
Please check screenshots on google drive
* How it looks on the **production** server [LINK](https://drive.google.com/file/d/1EmhB3DrxpMS-dwGYA_k3WSh5h24og2Xj/view?usp=sharing)
* How the response is looking on the **production** server [LINK](https://drive.google.com/file/d/1wKZuvnbljjY9r1Edd8i5comtTMcGVq2v/view?usp=sharing)
* How it looks on the **staging** server [LINK](https://drive.google.com/file/d/1Gc6WBmcvFq7pMzSO8C1uYXiB-Q6uEysF/view?usp=sharing)
* How the response is looking on the **staging** server [LINK](https://drive.google.com/file/d/128BaKo3E5VNtk47ZJT8QVJieJ0mt1nSz/view?usp=sharing)

**Comment by FlintOFF** [comment]
Found the reason!
The staging server works without 'New Relic'.
I removed 'New Relic' from the production server and after that, the issue has gone.
For me, the problem was resolved.
Thanks.

**Comment by morgoth** [comment]
Thanks for sharing.
I'll close it then.
